"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gesture_t(object):
    #__slots__ = ["Continue", "Stop", "SpeedUp", "SlowDown", "TurnLeft", "Forward", "TurnRight", "Backwardsa"]
    __slots__ = ["gesture_type"]

    __typenames__ = ["string"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.gesture_type = "Stop"

    def encode(self):
        buf = BytesIO()
        buf.write(gesture_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqhh", self.gesture_type))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gesture_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gesture_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gesture_t()
        self.gesture_type = struct.unpack(">qqqhh", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gesture_t in parents: return 0
        tmphash = (0xd4582742ffd4e8e8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gesture_t._packed_fingerprint is None:
            gesture_t._packed_fingerprint = struct.pack(">Q", gesture_t._get_hash_recursive([]))
        return gesture_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)


