/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package rob550.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class april_tag_data_t implements lcm.lcm.LCMEncodable
{
    public int id;
    public float dist;
    public float angle;
 
    public april_tag_data_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x307db312aa45e895L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(rob550.lcmtypes.april_tag_data_t.class))
            return 0L;
 
        classes.add(rob550.lcmtypes.april_tag_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.id); 
 
        outs.writeFloat(this.dist); 
 
        outs.writeFloat(this.angle); 
 
    }
 
    public april_tag_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public april_tag_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static rob550.lcmtypes.april_tag_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        rob550.lcmtypes.april_tag_data_t o = new rob550.lcmtypes.april_tag_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.id = ins.readInt();
 
        this.dist = ins.readFloat();
 
        this.angle = ins.readFloat();
 
    }
 
    public rob550.lcmtypes.april_tag_data_t copy()
    {
        rob550.lcmtypes.april_tag_data_t outobj = new rob550.lcmtypes.april_tag_data_t();
        outobj.id = this.id;
 
        outobj.dist = this.dist;
 
        outobj.angle = this.angle;
 
        return outobj;
    }
 
}

