/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package rob550.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class april_tag_t implements lcm.lcm.LCMEncodable
{
    public int id;
    public float x;
    public float y;
 
    public april_tag_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfeabb0c4bc39ff26L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(rob550.lcmtypes.april_tag_t.class))
            return 0L;
 
        classes.add(rob550.lcmtypes.april_tag_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.id); 
 
        outs.writeFloat(this.x); 
 
        outs.writeFloat(this.y); 
 
    }
 
    public april_tag_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public april_tag_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static rob550.lcmtypes.april_tag_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        rob550.lcmtypes.april_tag_t o = new rob550.lcmtypes.april_tag_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.id = ins.readInt();
 
        this.x = ins.readFloat();
 
        this.y = ins.readFloat();
 
    }
 
    public rob550.lcmtypes.april_tag_t copy()
    {
        rob550.lcmtypes.april_tag_t outobj = new rob550.lcmtypes.april_tag_t();
        outobj.id = this.id;
 
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        return outobj;
    }
 
}

